version: '3'
services:
  app:
    container_name: lemoncash
    image: lemoncash:v1
    build: .
    networks:
      - mynetwork
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/redis-service/logs
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge