server:
  servlet:
    context-path:
      /api/lemon-fo
  port: 8080
spring:
    redis:
      database: 0
      host: redis
      port: 6379
      password:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
lemon-fo:
  authorization:
    limit-time-range: 10
    limit-request: 5
fuck-off:
  base-url: https://www.foaas.com/
  name-company-url: ballmer/%s/%s/%s
  company-url: anyway/%s/%s
  name-url:  yoda/%s/%s
  from-url: dumbledore/%s